# Generated by Django 5.1.2 on 2024-10-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking_app', '0002_task_description_task_priority_task_status_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('edit_task', 'Can edit task')]},
        ),
    ]
