# Generated by Django 5.1.2 on 2024-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking_app', '0005_rename_text_comment_content_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
