# Generated by Django 5.1.2 on 2024-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking_app', '0006_task_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='task_media/'),
        ),
    ]
