# Generated by Django 5.1.2 on 2024-11-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking_app', '0007_task_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
